// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeT2SfoieLzefx_5WVX-9qv4sf8UYW34A',
    appId: '1:145733219568:android:306e7ab633880622583e35',
    messagingSenderId: '145733219568',
    projectId: 'grocery-app-1a0c1',
    storageBucket: 'grocery-app-1a0c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj5IHc8kFpDhXNHjxmmX0Z2jvGqEAbgBM',
    appId: '1:145733219568:ios:2689e62e9238c681583e35',
    messagingSenderId: '145733219568',
    projectId: 'grocery-app-1a0c1',
    storageBucket: 'grocery-app-1a0c1.appspot.com',
    androidClientId: '145733219568-9o9ulr44rugkoe80ulr1b5beijjatldf.apps.googleusercontent.com',
    iosClientId: '145733219568-k7edejcdmjcac0jrt66rctr1vt90nsm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdmin',
  );
}
